In [1]:
import numpy as np

## <u>**Exercice 1**</u>

### <u>PARTIE A</u>

Créer un tableau depuis la liste [1.6, 0.5, 7.4, 22.3] et stocker le dans la variable « vec ».
 * Afficher le contenu de la variable « vec »
 * Afficher le type de données du tableau « vec », sa forme, sa dimension et sa longueur.
 * Afficher le troisième élément du tableau.
 * Modifier la valeur « 0.5 » par « 3.8 ».
 * Calculer la taille de la mémoire du tableau.
 * Convertir le type du tableau vers « int »
 * Calculer la taille de la mémoire du tableau après la conversion du type.
 * Sauvegarder le tableau dans un fichier texte.

In [2]:
vec = np.array([1.6, 0.5, 7.4, 22.3])
print("vec:", vec)
print("Le type de vec est", vec.dtype)
print("Le 3e element de vec est", vec[2])
vec[1] = 3.8 #modification valeur dans le tableau

vec: [ 1.6  0.5  7.4 22.3]
Le type de vec est float64
Le 3e element de vec est 7.4


In [3]:
print("La taille de mémoire du tableau (float) est:", vec.nbytes)
vec = vec.astype(int)
print("Nouveau type:", vec.dtype) #vérification du changement en int
print("La taille de mémoire du tableau (int) est:", vec.nbytes)
np.savetxt('vec.txt', vec)

La taille de mémoire du tableau (float) est: 32
Nouveau type: int32
La taille de mémoire du tableau (int) est: 16


### <u>PARTIE B</u>
Créer une matrice « mat » depuis la liste [[0, 3, 6, 9], [5, 10, 15, 20], [30, 40, 50, 60]]
 * Afficher le contenu de la variable « mat »
 * Afficher le type de données de la matrice « mat », sa forme, sa dimension et sa longueur.
 * Pouvez-vous obtenir la dimension et la longueur à partir de la forme ?
 * Créer la matrice mat_1 extraite de mat telle que i >= 1, j <=2.
 * Modifier la matrice « mat » afin que sa dernière ligne soit divisée par 10 et que sa première colonne soit multipliée par 2.

In [4]:
mat = np.array([[0, 3, 6, 9], [5, 10, 15, 20], [30, 40, 50, 60]])
print(mat)
print('Type:', mat.dtype)
print('Forme:', mat.shape)
print('Dimension:', mat.ndim)
print('Longueur:', mat.size) #correspond au nombre d'éléments dans la matrice

[[ 0  3  6  9]
 [ 5 10 15 20]
 [30 40 50 60]]
Type: int32
Forme: (3, 4)
Dimension: 2
Longueur: 12


In [5]:
mat_1 = mat.reshape(6,2)
print(mat_1)
# On veut un nombre de colonnes <=2 donc à moins de faire un vecteur colonne type (12,1), j'ai choisi
# de faire un tabelau à deux dimensions (6,2)

[[ 0  3]
 [ 6  9]
 [ 5 10]
 [15 20]
 [30 40]
 [50 60]]


In [6]:
mat[2,:] = mat[2,:]/10
mat[:,0] = mat[:,0]*2

print(mat)

[[ 0  3  6  9]
 [10 10 15 20]
 [ 6  4  5  6]]


### <u>PARTIE C</u>

Créer un tableau multidimensionnel « nd_vec » d’une dimension > 2
* Afficher le contenu de « nd_vec »
* Afficher le type de données du tableau « nd_vec », sa forme, sa dimension et sa longueur.
* Pouvez-vous obtenir la dimension et la longueur à partir de la forme ?
* Afficher un élément de ce tableau ainsi qu’un sous tableau. 

In [ ]:
nd_vec = 

## <u>**Exercice 2**</u>

* Créer un tableau 1D vide de taille 10 et de type « int » ; observer les valeurs du tableau.
* Créer un tableau 2D vide de dimension (3x3) et de type « float » ; observer les valeurs du tableau.
* Créer un tableau de 3 dimensions (3x3x3) initialiséavec des zéros « 0 ». 
* Créer une matrice de taille (5x5) comportant des uns « 1 ».
* Créer un tableau de taille (10x10) initialisé avec la valeur « np.inf »
* Créer une matrice d’identité de taille (4x4).
* Créer une matrice dont la diagonale est égale à [2, 3, 4, 5] et des 0 ailleurs. 

In [7]:
onedim_arr = np.empty((10,1), dtype=int)
#print("Matrice 1D:", onedim_arr)

twodims_arr = np.empty((3,3), dtype=float)
#print("Matrice 2D:", twodims_arr)

threedims_arr = np.zeros((3,3,3))

mat_2 = np.zeros((5,5))+1
#print(mat_2)

arr = np.array(np.zeros((10,10))+np.inf)
#print(arr)

mat_id = np.identity(4)
#print(mat_id)

np.fill_diagonal(mat_id, [2,3,4,5])
#print(mat_id)

## <u>**Exercice 3**</u>

* Créer un tableau comportant la série d’entiers de 5 à 25 : [5, 6, 7, ... , 23,24,25]
* Créer un tableau contenant tous les entiers pairs entre 100 et 150 inclus.
* Créer un tableau qui comporte les dates du mois de Février 2019, ce tableau est de type « datetime64[D] »
* Créer un tableau de dix éléments équidistants entre 2 et 5 inclus.
* Soit la fonction $y=f(x)=(\exp(x)-\exp(-x))/(\exp(x)+\exp(-x))$.
* Créer des tableaux x, y qui contiennent respectivement 50 valeurs réparties uniformément sur [-5, 5] et l’évaluation de la fonction sur ces valeurs.
* Ecrire un programme NumPy qui permet de générer un nombre aléatoire entre 0 et 1.
* Créer un tableau de la dimension et de la taille de votre choix contenant des valeurs entre 34 et 76.
* Faites un tableau de forme (3, 5) avec des nombres aléatoires à partir d'une distribution normale standard (une distribution normale avec une moyenne 0 et une variance 1).
* Créer une matrice (10x5) comportant des entiers aléatoires entre 0 et 100.
    * Standardiser cette matrice telle que chaque colonne aura une moyenne nulle et un écart type égal à 1

In [9]:
tableau = np.array(np.arange(5,26,1))
tableau2 = np.array(np.arange(100,151,2))
tableau3 = np.array(np.arange('2019-02', '2019-03', dtype='datetime64[D]'))
tableau4 = np.array(np.linspace(2,5,10))

In [10]:
def f(x):
    return (np.exp(x)-np.exp(-x))/(np.exp(x)+np.exp(-x))

x = np.array(np.linspace(-5,5,50))
y = f(x)

In [12]:
import random

def nb_aleatoire():
    '''
    Cette fonction ne prend aucun paramètre en entrée mais permet de
    générer un nombre aléatoire entre 0 et 1 grâce à la fonction random
    du module éponyme.
    '''
    return random.random()

0.25870080465644685

In [13]:
tableau5 = np.random.normal(0, 1, size=(3,5))
tableau6 = np.random.randint(0,100,size=(10,5))

## <u>**Exercice 4**</u>

* Créer une matrice aléatoire 10x10
    * Sélectionner l'élément dans la première ligne et la première colonne.
    * Mettre l'élément de la dernière ligne et de la dernière colonne à -1.
    * Sélectionner les éléments de la deuxième ligne.
    * Sélectionner les éléments de la troisième colonne.
    * Remplacer tous les éléments de la deuxième ligne par 0.
* Ecrire un programme NumPy pour inverser un tableau (le premier élément devient le dernier)
* Ecrire un programme NumPy pour créer un tableau 2D avec 1 sur la bordure et 0 à l'intérieur
* Ecrire un programme NumPy pour créer une matrice 8x8 et remplissez là avec un motif en damier

In [22]:
mat_al = np.random.randint(0,10,size=(10,10))
print('Matrice entière:\n', mat_al)
mat_al[-1,-1] = -1 #mat_al[9,9] fonctionne aussi mais -1 désigne d'office le dernier élément
print('Matrice avec changement:\n', mat_al) #le 3 est devenu -1
print('Deuxième ligne:', mat_al[1,:])
print('Troisième colonne:', mat_al[:,2])
mat_al[-1,:] = 0
print('Changement dernière ligne:\n', mat_al)

Matrice entière:
 [[8 6 3 2 0 8 6 2 0 4]
 [6 2 7 8 1 2 7 6 4 0]
 [9 8 8 5 8 9 2 4 8 8]
 [2 9 9 2 0 3 0 7 9 0]
 [5 5 2 8 0 2 8 4 4 7]
 [0 3 4 1 9 4 9 9 2 5]
 [7 9 5 1 1 8 6 4 7 1]
 [6 3 8 6 2 6 3 1 5 1]
 [4 0 7 9 1 1 6 7 9 4]
 [0 0 7 1 2 7 7 2 5 6]]
Matrice avec changement:
 [[ 8  6  3  2  0  8  6  2  0  4]
 [ 6  2  7  8  1  2  7  6  4  0]
 [ 9  8  8  5  8  9  2  4  8  8]
 [ 2  9  9  2  0  3  0  7  9  0]
 [ 5  5  2  8  0  2  8  4  4  7]
 [ 0  3  4  1  9  4  9  9  2  5]
 [ 7  9  5  1  1  8  6  4  7  1]
 [ 6  3  8  6  2  6  3  1  5  1]
 [ 4  0  7  9  1  1  6  7  9  4]
 [ 0  0  7  1  2  7  7  2  5 -1]]
Deuxième ligne: [6 2 7 8 1 2 7 6 4 0]
Troisième colonne: [3 7 8 9 2 4 5 8 7 7]
Changement dernière ligne:
 [[8 6 3 2 0 8 6 2 0 4]
 [6 2 7 8 1 2 7 6 4 0]
 [9 8 8 5 8 9 2 4 8 8]
 [2 9 9 2 0 3 0 7 9 0]
 [5 5 2 8 0 2 8 4 4 7]
 [0 3 4 1 9 4 9 9 2 5]
 [7 9 5 1 1 8 6 4 7 1]
 [6 3 8 6 2 6 3 1 5 1]
 [4 0 7 9 1 1 6 7 9 4]
 [0 0 0 0 0 0 0 0 0 0]]


In [39]:
def inversetab(arr):
    '''
    Cette fonction prend en paramètre un tableau qu'importe
    sa dimension. Elle renvoie le tableau passé en input avec
    ses éléments inversés.
    '''
    arr_flipped = np.flip(arr)
    return arr_flipped

def bord_int(nb_row, nb_col):
    '''
    Cette fonction prend en entrée un nombre de lignes
    et un nombre de colonnes. Elle renvoie un tableau
    avec des 1 sur les bordures extérieures(1e colonne, 1e ligne,
    dernière colonne, dernière ligne).
    '''
    arr = np.zeros((nb_row, nb_col))
    arr[0,:] = 1
    arr[:,0] = 1
    arr[-1,:] = 1
    arr[:,-1] = 1
    return arr

def damier():
    '''
    Cette fonction ne prend aucun paramètre en entrée et va
    créer un array avec un motif en damier.
    '''
    arr = np.empty((8,8), dtype='str')
    for i in range(8):
        for j in range(8):
            if (i+j)%2 == 0:
                arr[i,j] = 'X'
            else:
                arr[i,j] = 'O'
    return arr

## <u>**Exercice 5**</u>

* Ecrire un programme NumPy dans lequel vous allez:
    * Définir un tableau à une dimension de la taille de votre choix
    * Calculer l'écart-type des valeurs présentes dans ce tableau
    * Chercher les valeurs et les indices des éléments qui sont supérieurs à la moyenne+1.96\*ecart-type
    * Remplacer toutes ces valeurs par la valeur maximale du tableau
    * Chercher les valeurs et les indices des éléments qui sont inférieurs à la moyenne-1.96\*ecart-type
    * Remplacer toutes ces valeurs par la valeur minimale du tableau
    * Compter le nombre d'éléments égaux au maximum et le nombre d'éléments égaux au maximum
    * Compter le nombre d'éléments différents de min ou de max

In [43]:
my_array = np.random.randint(10,50,size=(30,1))

def programme(arr):
    # Calcul de la moyenne et de l'écart-type
    std = arr.std()
    mean = arr.mean()
    
    # Définition des seuils
    seuil_sup = mean + (1.96*std)
    seuil_inf = mean - (1.96*std)
    
    # Définition des valeurs qu'il faudra remplacer
    valeur_max = arr.max()
    valeur_min = arr.min()
    
    # Recherche des valeurs
    for i in range(arr.shape[0]):
        if arr[i,:] > seuil_sup:
            arr[i,:] = valeur_max
        elif arr[i,:] < seuil_inf:
            arr[i,:] = valeur_min
    
    # Comptage des valeurs
    nb_valeurs_max = np.count_nonzero(arr == valeur_max)
    nb_valeurs_min = np.count_nonzero(arr == valeur_min)
    nb_valeurs_autres = np.count_nonzero(((arr != valeur_max) & (arr != valeur_min)))
    
    #Affichage
    print('Nombre de valeurs maximum:', nb_valeurs_max)
    print('Nombre de valeurs minimum:', nb_valeurs_min)
    print('Nombre de valeurs autres:', nb_valeurs_autres)

In [46]:
programme(my_array)
print(my_array.T) # Affichage en trabsposée pour une meilleure lecture des valeurs

Nombre de valeurs maximum: 1
Nombre de valeurs minimum: 2
Nombre de valeurs autres: 27
[[19 24 42 34 13 27 26 38 45 18 10 38 25 42 41 22 23 30 29 11 48 39 19 10
  41 22 40 18 18 13]]


## <u>**Exercice 6**</u>

* Ecrire un programme NumPy pour créer une matrice 3x3 avec des valeurs allant de 2 à 10
* Créer la matrice suivante sans saisir explicitement ses valeurs :
>```python
[1,6,11]
[2,7,12]
[3,8,13]
[4,9,14]
[5,10,15]
```
* Divisier le tableau `s=np.arange(25).reshape(5,5)` afin de séparer chaque colonne à part.
* Créer la matrice suivante en concaténant 3 tableaux unidimensionnel. Utiliser `np.arange` et `np.ones` pour la création des tableaux.
>```python
[7,8,9]
[1,1,1]
[12,18,2]
```

## <u>**Exercice 7**</u>

* Ecrire un programme qui trouve les positions des éléments non nuls dans un tableau.
* Ecrire un programme qui teste si aucun des éléments d'un tableau donné n'est nul
* Utiliser la fonction Numpy `np.pad` pour ajouter une bordure (remplie de 0) autour d'un tableau existant
* Utiliser la fonction `np.asarray` pour créer un tableau à partir d'un tuple ou une liste
* Tester la fonction `np.append` pour ajouter des éléments à la fin d'un tableau.
* Utiliser la fonction `np.in1d` pour tester si chaqye élément d'un tableau 1-D est également présent dans un second tableau
* Utiliser la fonction `np.intersect1d` pour trouver des valeurs communes entre deux tableaux
* Utiliser la fonction `np.tile` pour construire un tableau en répétant les éléments d'un auyre tableau
* Utiliser la fonction `bincount` pour compter le nombre d'occurennces de chaque valeur d'un tableau de valeurs positives

## <u>**Exercice 8**</u>

Utiliser la libairie NumPy pour lire un fichier représentant un dataset. Utiliser la fonction `gen.genfromtxt()` pour lire le fichier *titanic.csv* dans un tableau que l'on nommera *données*
* Afficher le type de la variable données en utilisant la fonction `type()`
* Afficher sa dimension, sa forme, etc.
* Apporter des modifications à votre base et sauvegarder la nouvelle base dans un fichier _titanic\_mod.csv_